


- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

  # Starter pipeline
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'Service Conection Alex'
    backendAWSBucketName: 'waf5000'
    
    

- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'validate'